version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc --go_out=paths=source_relative:gen/go --go-grpc_out=paths=source_relative:gen/go ./proto/auth/auth.proto

